const $=(s)=>document.querySelector(s);
const icons={album:'<rect x="4" y="3" width="16" height="18" rx="2"/><path d="M8 3v18M12 8h4M12 12h4"/>',book:'<path d="M12 5C8 2 3 3 3 3v16s5-1 9 2c4-3 9-2 9-2V3s-5-1-9 2v16"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',plus:'<path d="M12 5v14M5 12h14"/>',lock:'<rect x="6" y="10" width="12" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v3"/>',arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',leaf:'<path d="M5 20C2 8 12 3 21 3c0 9-4 17-16 17Zm0 0L16 9"/>',image:'<rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="1"/><path d="m3 17 6-6 5 5 3-3 4 4"/>',spark:'<path d="m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z"/>'};
const icon=(name,size=18)=>`<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.leaf}</svg>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toLocaleDateString('sv-SE');
let db,items=[],tab='album',filter='all',sort='new',activeId=null,page=0,modalMode='',draft=null,toastTimer,recording=null,recTimer;
const seed=()=>[
{id:'sample-dog',title:'小蓝的月亮',words:'小狗想把月亮带回家，给妈妈当小夜灯。',parent:'蓝色小狗戴着红围巾。',date:'2026-09-23',original:'/assets/dog.svg',image:'/assets/dog.svg',sample:true,kind:'dog',story:{ready:true,delivered:Date.now(),setting:'蓝色小狗和月亮一起散步。',adjustments:0,variants:{},previous:{},position:0}},
{id:'sample-garden',title:'会唱歌的花园',words:'每一朵花，都有自己的声音。',date:'2026-09-21',original:'/assets/garden.svg',image:'/assets/garden.svg',sample:true,kind:'garden'},
{id:'sample-space',title:'去星星上做客',words:'我的火箭里，要带上小熊和饼干。',date:'2026-09-18',original:'/assets/space.svg',image:'/assets/space.svg',sample:true,kind:'space'}];
function transaction(mode,fn){return new Promise((resolve,reject)=>{const tx=db.transaction('data',mode);let r;try{r=fn(tx.objectStore('data'))}catch(e){reject(e);return}tx.oncomplete=()=>resolve(r?.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('保存中断'));});}
async function save(){await transaction('readwrite',s=>s.put(items,'artworks'));}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3400)}
const current=()=>items.find(i=>i.id===activeId);
function navButton(id,name,glyph){return `<button data-action="nav" data-value="${id}" class="${tab===id?'active':''}">${icon(glyph)}${name}<span>${id==='album'?'01':id==='read'?'02':'03'}</span></button>`}
function render(){
 $('#app').innerHTML=`<aside class="sidebar"><div class="brand"><img class="brand-mark" src="/assets/logo.svg" alt=""><div>画活了<small>LITTLE ART, BIG STORIES</small></div></div><div class="side-label">每一笔，都值得被记住</div><nav class="nav">${navButton('album','我的画册','album')}${navButton('read','一起读','book')}${navButton('me','我的','user')}</nav><div class="side-note"><div class="sprout">${icon('leaf',33)}</div>不着急长大，<br>先把想象留下来。</div><div class="profile"><div class="avatar">${icon('user',19)}</div><div><strong>小小收藏家</strong><small>我们的画册</small></div></div></aside><main class="main"><header class="topbar"><span class="topbar-brand"><img src="/assets/logo.svg" alt="" width="28" height="28">画活了 <span style="margin:0 12px;color:#c0c3b4">/</span> ${tab==='album'?'我的画册':tab==='read'?'一起读':'我的'}</span><div class="lock">${icon('lock',13)} 仅在这台设备</div></header>${tab==='me'?profileView():albumView()}<footer class="footer"><span>画活了 · 每一幅画，都是一个小小世界</span><span>用想象，收藏童年</span></footer></main>`;
}
function albumView(){let visible=items.filter(i=>tab==='read'?i.story?.ready:filter==='story'?i.story?.ready:filter==='original'?!i.story?.ready:true);visible.sort((a,b)=>sort==='new'?b.date.localeCompare(a.date):a.date.localeCompare(b.date));return `<section class="page-head"><div><div class="eyebrow">${tab==='read'?'A LITTLE STORY TIME':'THE LITTLE GALLERY'}</div><h1>${tab==='read'?'把故事，再读一遍':'小小画册，大大世界'}</h1><p>${tab==='read'?'靠近一点，听听画里的小小冒险。':'收藏孩子的每一笔，也收藏每一笔背后的奇思妙想。'}</p></div><button class="primary" data-action="new">${icon('plus',17)} 留下一幅画</button></section>${tab==='album'?`<section class="hero"><div><div class="hero-tag">${icon('spark',13)} 从一幅画，到一个故事</div><h2>那些天马行空，<br>值得有一个小小的后来。</h2><p>拍下孩子的画，听听他的想法，<br>一起做成可以反复翻阅的故事。</p><button class="text-btn" data-action="sample">翻开四页示例 ${icon('arrow',15)}</button></div><div class="hero-art"><div class="paper"><img src="/assets/dog.svg" alt="手绘蓝色小狗示例"><small>一幅小画</small></div><div class="paper two"><img src="/assets/story-3.svg" alt="月亮下的小狗故事示例"><small>一场小小冒险</small></div><span class="doodle">✧</span><span class="tiny-note">让想象，轻轻翻一页 ↗</span></div></section>`:''}<div class="section-bar"><div class="filters">${tab==='album'?['all','story','original'].map((v,i)=>`<button data-action="filter" data-value="${v}" class="${filter===v?'active':''}">${['全部作品','有故事的画','原画记录'][i]}${v==='all'?`<em>${items.length}</em>`:''}</button>`).join(''):`<button class="active">我们的故事 <em>${visible.length}</em></button>`}</div><select class="sort" aria-label="作品排序"><option value="new" ${sort==='new'?'selected':''}>最新收藏优先</option><option value="old" ${sort==='old'?'selected':''}>最早收藏优先</option></select></div><section class="cards">${visible.length?visible.map(card).join(''):`<div class="empty">${icon('book',38)}<h2 style="margin-top:20px">${tab==='read'?'下一本故事，从一幅画开始':'这里等着下一份想象'}</h2><p>先留下画，也可以只是留下一段珍贵的原话。</p><button class="primary" data-action="${tab==='read'?'backAlbum':'new'}">${tab==='read'?'去画册看看':'留下一幅画'}</button></div>`}</section><div class="bottom-note">${icon('lock',12)} ${items.length} 幅小小想象，安静地收藏在这里</div>`}
function automaticTitle(description,date){const text=String(description||'').trim().replace(/\s+/g,' ').replace(/^[“”"'「」]+/,'');return text?Array.from(text.split(/[。！？!?\n]/)[0]).slice(0,16).join('')||'小小想象':`${date} 的小小想象`;}
function card(i){return `<button class="card" data-action="detail" data-id="${esc(i.id)}"><div class="art-wrap"><img src="${esc(i.image)}" alt="${esc(i.title)}"><span class="badge ${i.story?.ready?'':'neutral'}">${icon(i.story?.ready?'book':i.job?'spark':'image',11)}${i.story?.ready?'故事可以读了':i.job?(i.job.real?'AI 任务待查看':'故事演示准备中'):'原画已收藏'}</span></div><div class="card-title"><h3>${esc(i.title)}</h3><span class="card-date">${esc(i.date)}</span></div><p class="quote">${i.words?'“'+esc(i.words)+'”':esc(i.parent||'有些想象，不需要解释。')}</p><div class="card-foot"><span>${i.sample?'示例插画':'家长记录 · 仅本机'}</span><span>${i.story?.ready?'一起读 ↗':'看看这幅画 ↗'}</span></div></button>`}
function profileView(){return `<section class="page-head"><div><div class="eyebrow">A PLACE FOR LITTLE WONDERS</div><h1>我们的收藏角</h1><p>每一份记录，都由你来决定如何保存。</p></div></section><div class="panel"><h2>小小收藏家的画册</h2><p>记录保存在当前浏览器。清理浏览器数据或更换设备后可能无法找回，请及时导出。</p><div class="stats"><div><strong>${items.length}<small> / 30</small></strong><small>幅原画</small></div><div><strong>${items.filter(i=>i.story?.ready).length}</strong><small>本故事</small></div></div></div><div class="panel"><div class="settings-row"><div><h3>订单与购买</h3><p>暂未开放购买。</p></div><button disabled>暂未开放购买</button></div><div class="settings-row"><div><h3>导出我的记录</h3><p>下载包含原图、文字和录音的 JSON 备份。</p></div><button data-action="backup">导出备份 ↗</button></div><div class="settings-row"><div><h3>隐私与数据说明</h3><p>AI 授权前仅存本机；授权后处理图和文字发送至 Poixe。</p></div><button data-action="privacy">查看说明 ↗</button></div></div>`}
// Keep dialogs within the visible viewport after iOS input zoom or keyboard changes.
function syncModalViewport(){const overlay=$('.overlay'),v=window.visualViewport;if(!overlay||!v)return;Object.assign(overlay.style,{left:v.offsetLeft+'px',top:v.offsetTop+'px',width:v.width+'px',height:v.height+'px',right:'auto',bottom:'auto'});}
window.visualViewport?.addEventListener('resize',syncModalViewport);
window.visualViewport?.addEventListener('scroll',syncModalViewport);
function openModal(title,body,wide=false){$('#modal-root').innerHTML=`<div class="overlay"><section class="modal ${wide?'wide':''}" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="modal-head"><h2>${title}</h2><button class="close" data-action="close" aria-label="关闭">×</button></div>${body}</section></div>`;document.body.style.overflow='hidden';syncModalViewport();$('.close')?.focus({preventScroll:true})}
function closeModal(){if(recording&&recording.state==='recording'){recording.stop();recording.stream.getTracks().forEach(t=>t.stop());}clearTimeout(recTimer);recording=null;$('#modal-root').innerHTML='';document.body.style.overflow='';modalMode='';draft=null;}
function edit(){if(items.length>=30)return toast('已达到 30 幅上限，请先导出或删除部分作品。');draft={};modalMode='edit';openModal('留下一幅小小想象',`<p class="muted">先把画留下来。故事，可以慢慢讲。</p><form id="art-form"><label class="upload" style="margin-top:18px"><div id="upload-preview">${icon('image',35)}</div><span id="upload-label">选择一幅画 · JPEG / PNG / WebP，最大 10 MB</span><input type="file" id="image-file" accept="image/jpeg,image/png,image/webp" aria-label="选择画作" required></label><div class="editor-tools" role="group" aria-label="调整画作"><button type="button" data-action="rotate">旋转 90°</button><button type="button" data-action="crop">居中裁成方形</button><button type="button" data-action="restore">恢复原图</button></div><label class="field">说说这幅画 <span class="muted">· 可选</span><textarea name="parent" maxlength="500" placeholder="比如：蓝色和粉色的小伙伴，想带小兔子一起去探险。"></textarea></label><p class="muted" style="margin-top:8px">写一句就好，做故事时会直接沿用。也可以不写，先把画收藏起来。</p><details class="more-records"><summary>更多记录 <span>名字、日期、孩子原话或录音 · 可选</span></summary><label class="field">画的名字<input name="title" type="text" maxlength="40" placeholder="不用填写，会根据描述自动命名"></label><label class="field">创作日期<input type="date" name="date" value="${today()}"></label><label class="field">单独记下孩子的原话 · 可选<textarea name="words" maxlength="500" placeholder="想保留孩子说过的话时，再记在这里。"></textarea></label><div class="settings-row"><div><strong style="font-size:12px">留住孩子的声音 · 可选</strong><p class="muted">最长 60 秒，仅保存和回听，不转写、不用于生成。</p></div><button type="button" class="secondary" data-action="record" id="record-btn">开始录音</button></div><div id="audio-preview"></div></details><label class="check"><input type="checkbox" required>我是监护人，理解原始记录默认保存在当前浏览器、没有云端备份，可导出或删除；AI 发送另行授权。</label>${aiNotice()}<label class="check"><input type="checkbox" id="ai-upload-consent">同意将处理图和文字发送给 Poixe 及其上游 AI 生成故事，已阅读数据使用与费用说明。</label><div class="actions"><button type="submit" name="intent" value="save" class="secondary">只保存原画</button><button type="submit" name="intent" value="generate" class="primary" id="save-btn">${icon('spark',16)} 生成故事</button></div></form>`)}
async function readFile(file){return new Promise((resolve,reject)=>{const r=new FileReader;r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
async function loadImage(src){return new Promise((resolve,reject)=>{const im=new Image;im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('无法读取这张图片'));im.src=src})}
async function selectImage(file){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){$('#image-file').value='';return toast('请选择不超过 10 MB 的 JPEG、PNG 或 WebP 图片。')}const original=await readFile(file);await loadImage(original);Object.assign(draft,{original,image:original,fileName:file.name});previewImage()}
function previewImage(){$('#upload-preview').innerHTML=`<img src="${draft.image}" alt="处理图预览">`;$('#upload-label').textContent='点击可重新选择 · 编辑只作用于副本'}
async function transformImage(mode){if(!draft?.image)return toast('请先选择一幅画');if(mode==='restore'){draft.image=draft.original;previewImage();return}const im=await loadImage(draft.image),c=document.createElement('canvas'),ctx=c.getContext('2d');if(mode==='rotate'){c.width=im.height;c.height=im.width;ctx.translate(c.width/2,c.height/2);ctx.rotate(Math.PI/2);ctx.drawImage(im,-im.width/2,-im.height/2)}else{c.width=c.height=Math.min(im.width,im.height);ctx.drawImage(im,(im.width-c.width)/2,(im.height-c.height)/2,c.width,c.height,0,0,c.width,c.height)}draft.image=c.toDataURL('image/png');previewImage()}
async function saveArtwork(form,intent='generate'){if(form.dataset.saving)return;const generateNow=intent==='generate';if(generateNow&&!$('#ai-upload-consent')?.checked)return toast('请先确认 AI 使用说明；也可以选择只保存原画。');if(!draft?.original)return toast('请先选择一幅画');if(recording?.state==='recording')return toast('请先结束录音，再保存。');form.dataset.saving='1';form.querySelectorAll('button[type=submit]').forEach(b=>b.disabled=true);const data=new FormData(form),item={id:crypto.randomUUID(),title:data.get('title').trim()||automaticTitle(data.get('parent'),data.get('date')||today()),words:data.get('words').trim(),parent:data.get('parent').trim(),date:data.get('date')||today(),...draft,consentAt:new Date().toISOString()};items.unshift(item);try{await save()}catch(e){items=items.filter(i=>i.id!==item.id);delete form.dataset.saving;form.querySelectorAll('button[type=submit]').forEach(b=>b.disabled=false);throw e}activeId=item.id;closeModal();render();if(generateNow){await realGenerate({disabled:false},{consent:true,setting:(item.parent||item.words||'围绕原画中的主体，发生一件温和的小事。').slice(0,150)});}else{toast('原画已保存，随时可以回来查看。');}}
async function record(){if(recording?.state==='recording'){recording.stop();return}if(!navigator.mediaDevices?.getUserMedia)return toast('当前浏览器无法录音，可以填写文字后继续保存。');try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});if(modalMode!=='edit'){stream.getTracks().forEach(t=>t.stop());return}const chunks=[];recording=new MediaRecorder(stream);recording.ondataavailable=e=>chunks.push(e.data);recording.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());clearTimeout(recTimer);const blob=new Blob(chunks,{type:recording?.mimeType||chunks[0]?.type||'audio/webm'});recording=null;if(modalMode!=='edit')return;if(blob.size>10*1024*1024)return toast('录音超过 10 MB，请重录。');draft.audio=await readFile(blob);$('#audio-preview').innerHTML=`<audio controls src="${draft.audio}" style="width:100%;margin-top:15px"></audio>`;$('#record-btn').textContent='重新录音'};recording.start();$('#record-btn').textContent='结束录音';recTimer=setTimeout(()=>recording?.state==='recording'&&recording.stop(),60000)}catch{toast('未能获得麦克风权限，你仍可用文字记录或直接保存。')}}
function detail(){const i=current();if(!i)return;modalMode='detail';openModal('这一幅，值得记住',`<div class="detail-grid"><div><img class="detail-image" src="${esc(i.image)}" alt="${esc(i.title)}"><p class="source">${i.sample?'示例插画':'处理图 · 原始文件独立保留'} · ${esc(i.date)}</p><button class="text-btn" data-action="original">下载原图 ${icon('arrow',13)}</button></div><div class="detail-copy"><div class="eyebrow">A LITTLE PIECE OF IMAGINATION</div><h3>${esc(i.title)}</h3><p class="quote-full">${i.words?'“'+esc(i.words)+'”':esc(i.parent||'有些想象，不需要解释。')}</p><p class="source">${i.sample?'预设示例文字':i.words?'家长记录的孩子原话':'家长描述'}</p>${i.words&&i.parent?`<p class="muted">家长描述：${esc(i.parent)}</p>`:''}${i.audio?`<audio controls src="${esc(i.audio)}" style="width:100%;margin-top:15px"></audio><p class="source">孩子原声 · 未转写</p>`:''}<div class="notice">画已收藏。是否做成故事，由你和孩子一起决定。</div><button class="primary" data-action="${i.story?.ready?'read':i.job?'status':'setup'}">${icon(i.story?.ready?'book':'spark',16)} ${i.story?.ready?'一起读这个故事':i.job?(i.job.real?'查看生成进度':'查看演示进度'):'一起做个故事'}</button></div></div><div class="actions"><button class="text-btn danger left" data-action="delete">删除这幅作品</button><button class="secondary" data-action="close">回到画册</button></div>`,true)}
function setup(){const i=current();if(!i)return;if(!i.sample){realSetup();return;}modalMode='setup';openModal('故事，从一句想象开始',`<div class="steps"><span class="on">01 确认设定</span><span>02 四页故事</span><span>03 一起阅读</span></div><p class="muted">示例画作：${esc(i.title)}。本次使用预设图文，不调用 AI。</p><label class="field">一句话设定<textarea id="setting" maxlength="150">${esc(i.words)}</textarea></label><p class="source">来源：预设示例，可编辑体验确认流程。演示输出使用固定故事，不随设定生成。</p><div class="preview-grid">${[0,1,2,3].map((n)=>`<div><img src="${pageImage(i,n)}" alt="第 ${n+1} 页示例"><small>${n===0?'01 原画记录':`0${n+1} 预设续画`}</small></div>`).join('')}</div><div class="notice"><strong>一本静态图文故事，共四页，不含动画。</strong><br>正式产品每本 ¥9.90，首次完整体验免费；含首次交付起 30 天内 2 次成功单页图片调整。当前暂未开放购买。</div><label class="check"><input id="demo-consent" type="checkbox">我了解这是预设故事演示，不代表真实模型效果，也不消耗正式体验资格。</label><div class="actions"><button class="secondary" data-action="detail" data-id="${i.id}">只留住这幅画</button><button class="primary" data-action="generate">开始免费演示 ${icon('arrow',15)}</button></div>`)}
async function generate(){const i=current();if(!$('#demo-consent').checked)return toast('请先确认演示说明');const setting=$('#setting').value.trim();if(!setting)return toast('请先写一句故事设定');if(items.some(a=>a.job))return toast('还有一个故事演示正在进行，请稍后再试。');i.job={started:Date.now(),setting,id:crypto.randomUUID()};await save();render();status()}
function status(){const i=current();if(i?.job?.real){realStatus();return;}if(!i?.job){if(i?.story?.ready)reader();return}modalMode='status';let phase=Math.min(2,Math.floor((Date.now()-i.job.started)/2500));openModal('小小故事，正在准备',`<div class="wait-graphic">✧</div><h3 class="wait-title">${['正在排好故事的开头','正在准备三页示例续画','正在整理四页故事'][phase]}</h3><p class="muted" style="text-align:center">画已保存。演示完成后会出现在画册里，<br>可以稍后回来一起读。</p><div class="steps">${['排队','准备预设图文','整理完成'].map((s,n)=>`<span class="${phase===n?'on':''}">${s}</span>`).join('')}</div><p class="source">本地模拟状态 · 无模型调用与真实审核<br>任务 ${i.job.id.slice(0,8)} · ${new Date(i.job.started).toLocaleTimeString('zh-CN')}</p><div class="actions"><button class="text-btn left" data-action="cancel-job">取消本次演示</button><button class="primary" data-action="close">返回画册</button></div>`)}
async function tick(){await pollRealJobs();let changed=false;for(const i of items){if(i.job&&!i.job.real&&Date.now()-i.job.started>=7500){i.story={ready:true,setting:i.job.setting,delivered:Date.now(),adjustments:0,variants:{},previous:{},position:0};delete i.job;changed=true}}if(changed){await save();render();if(modalMode==='status'&&current()?.story?.ready){page=0;reader()}toast('示例故事准备好了，随时回来一起读')}else if(modalMode==='status'&&current()?.job)status()}
const captions={dog:['小狗想把月亮带回家，给妈妈当小夜灯。','小蓝走进安静的树林。树梢上，月亮露出半张脸，好像也想和它玩捉迷藏。','小蓝来到池塘边，水里也藏着一轮月亮。它没有跳进去，只轻轻坐下，陪月亮看了一会儿星星。','回家的路上，月亮一直跟着小蓝。原来不用把月亮装进口袋，它也可以陪自己走很远。'],garden:['每一朵花，都有自己的声音。','风经过花园，粉色的小花轻轻摇头。它听见隔壁传来一个细细的声音，像雨滴落在叶子上。','紫色的花没有急着唱。它先听了听朋友的声音，再把自己小小的旋律，放进风里。','傍晚，每一朵花都唱得不一样。风把那些小小的声音装在一起，变成了花园自己的歌。'],space:['我的火箭里，要带上小熊和饼干。','小火箭穿过软软的云，来到一颗安静的星星旁。窗外闪着一点光，好像有人在打招呼。','星星上没有饼干店。小火箭里的朋友想了想，把带来的饼干分成两半，留一半给新朋友。','回家时，星星送来一小片温暖的光。小火箭慢慢飞着，窗外的夜空，比来时更亲切了。']};
function pageImage(i,n){if(i.story?.real)return n===0?i.story.sourceImage:i.story.pages[n-1].image;return n===0?i.image:i.kind==='dog'?`/assets/story-${n}.svg`:i.image}
function pageCaption(i,n){if(i.story?.real)return n===0?(i.story.words||i.story.setting):i.story.pages[n-1].text;return n===0?i.words:(captions[i.kind]||captions.dog)[n]}
function reader(){const i=current();if(!i?.story?.ready)return;modalMode='reader';page=Math.max(0,Math.min(3,page));i.story.position=page;save().catch(()=>toast('阅读位置保存失败'));const variant=i.story.variants[page];openModal(esc(i.title),`<div class="reader-top"><span>${page===0?'01 / 原画与原话':'0'+(page+1)+(i.story.real?' / AI 生成续页':' / 预设故事续页')}</span><span>${i.story.real?'AI 创作 · 请家长先阅':'静态图文 · 故事示例'}</span></div><img class="reader-image" style="${variant==='warm'?'filter:sepia(.28) saturate(1.15)':variant==='soft'?'filter:saturate(.65) brightness(1.04)':''}" src="${pageImage(i,page)}" alt="${esc(i.title)}第 ${page+1} 页"><p class="reader-copy">${esc(pageCaption(i,page))}</p><div class="reader-nav"><button class="secondary" data-action="prev" ${page===0?'disabled':''}>← 上一页</button><div class="dots">${[0,1,2,3].map(n=>`<button class="${page===n?'active':''}" data-action="page" data-value="${n}" aria-label="第 ${n+1} 页"></button>`).join('')}</div><button class="secondary" data-action="next" ${page===3?'disabled':''}>下一页 →</button></div><p class="reader-label">${i.story.real?(page===0?(i.story.words?'原画 · 家长记录大意':'原画 · 家长确认设定'):'AI 生成 · 请家长先阅'):(page===0?'示例原画 · 预设文字':'预设故事示例')} · ${page+1} / 4</p><div class="actions"><button class="text-btn left" data-action="detail" data-id="${i.id}">查看原画记录</button>${page>0&&!i.story.real?`<button class="secondary" data-action="adjust">调整这一页</button>`:''}<button class="primary" data-action="share">分享图片</button></div>`,true)}
function adjust(){const i=current(),expired=Date.now()-i.story.delivered>30*86400000;modalMode='adjust';openModal('给这一页，一点小变化',`<p class="muted">第 ${page+1} 页 · 剩余 ${Math.max(0,2-i.story.adjustments)} 次演示调整</p><div class="notice">正式规则：30 天内 2 次成功单页图片调整。成功生成可预览后即计次，保留旧图也计次。客观错误应走问题反馈，不占次数。</div><p class="muted">当前用本地色调变化演示版本采用和撤销，不调用 AI。</p><div class="adjust-options"><button class="secondary selected" data-action="tone" data-value="warm">暖一点的光</button><button class="secondary" data-action="tone" data-value="soft">柔一点的颜色</button></div><div class="actions">${Object.hasOwn(i.story.previous,page)?'<button class="text-btn left" data-action="undo">撤销最近采用的调整</button>':''}<button class="secondary" data-action="read">返回阅读</button><button class="primary" data-action="preview-adjust" ${expired||i.story.adjustments>=2?'disabled':''}>${expired?'调整期限已过':'生成演示预览'}</button></div>`)}
let pendingTone='warm';
async function previewAdjust(){const i=current();if(i.story.adjustments>=2||Date.now()-i.story.delivered>30*86400000)return toast('调整权益已用完或已过期');i.story.adjustments++;await save();modalMode='adjust-preview';openModal('看看这次的小变化',`<img class="reader-image" style="filter:${pendingTone==='warm'?'sepia(.28) saturate(1.15)':'saturate(.65) brightness(1.04)'}" src="${pageImage(i,page)}" alt="色调调整预览"><div class="notice">预览已成功，本次演示调整已计次。剩余 ${2-i.story.adjustments} 次；保留旧图也不会返还本次次数。</div><div class="actions"><button class="secondary" data-action="read">保留旧图</button><button class="primary" data-action="adopt">采用这张</button></div>`)}
function download(data,name){const url=typeof data==='string'?data:URL.createObjectURL(data),a=document.createElement('a');a.href=url;a.download=name;a.click();if(typeof data!=='string')setTimeout(()=>URL.revokeObjectURL(url),1000)}
function downloadJSON(data,name){download(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),name)}
function printStory(){const i=current();document.querySelector('.print-pages')?.remove();const el=document.createElement('div');el.className='print-pages';el.innerHTML=[0,1,2,3].map(n=>`<section class="print-page"><h1>${esc(i.title)}</h1><img src="${pageImage(i,n)}" style="${i.story.variants[n]==='warm'?'filter:sepia(.28) saturate(1.15)':i.story.variants[n]==='soft'?'filter:saturate(.65) brightness(1.04)':''}"><p>${esc(pageCaption(i,n))}</p><small>画活了 · ${n===0?'原画记录':i.story.real?'AI 生成续页':'预设故事续页'} · ${i.story.real?'AI 生成 · 请家长先阅':'预设故事示例'} · ${n+1} / 4</small></section>`).join('');document.body.append(el);Promise.all([...el.querySelectorAll('img')].map(im=>im.decode())).then(()=>window.print()).catch(()=>toast('导出图片加载失败，请重试'))}
async function share(){
 const i=current();if(!i?.story?.ready)return;
 // Snapshot the adopted version so all four tiles and captions belong to one export.
 const snapshot=structuredClone(i),images=await Promise.all([0,1,2,3].map(n=>loadImage(pageImage(snapshot,n))));
 const c=document.createElement('canvas');c.width=c.height=1600;const x=c.getContext('2d');
 const rounded=(left,top,w,h,r,fill)=>{x.beginPath();x.roundRect(left,top,w,h,r);x.fillStyle=fill;x.fill();};
 const star=(cx,cy,r,color)=>{x.save();x.translate(cx,cy);x.beginPath();for(let k=0;k<8;k++){const angle=k*Math.PI/4,rad=k%2?r*.35:r;x.lineTo(Math.cos(angle)*rad,Math.sin(angle)*rad);}x.closePath();x.fillStyle=color;x.fill();x.restore();};
 x.fillStyle='#fff8eb';x.fillRect(0,0,1600,1600);
 for(let k=0;k<26;k++){x.beginPath();x.arc(20+(k*137)%1560,18+(k*211)%1560,3+k%3,0,Math.PI*2);x.fillStyle=['#efdaca','#dbe6cd','#f4e4b4'][k%3];x.fill();}
 rounded(44,30,160,52,26,'#e4ecd8');x.fillStyle='#58734c';x.font='bold 28px sans-serif';x.fillText('画活了',80,66);
 x.fillStyle='#967e69';x.font='22px sans-serif';x.fillText('把小小想象，变成一个故事',226,65);
 star(1498,59,21,'#e4b65e');star(1537,91,12,'#dba6aa');
 x.fillStyle='#526547';x.font='bold 36px sans-serif';x.fillText(snapshot.title,48,123,1430);
 const wrap=(text,width)=>{const lines=[];let line='';for(const ch of String(text)){if(ch==='\n'){lines.push(line);line='';continue}if(line&&x.measureText(line+ch).width>width){lines.push(line);line=ch}else line+=ch}if(line)lines.push(line);return lines;};
 const colors=['#e8efdd','#f8e7dc','#e5eef2','#f3e5ef'];
 images.forEach((im,n)=>{
  const left=44+(n%2)*768,top=153+Math.floor(n/2)*677,w=744,h=653;
  x.save();x.shadowColor='#917d5c18';x.shadowBlur=14;x.shadowOffsetY=5;rounded(left,top,w,h,25,'#fffefb');x.restore();
  x.save();x.beginPath();x.roundRect(left,top,w,h,25);x.clip();x.fillStyle=colors[n];x.fillRect(left,top,w,57);x.restore();
  rounded(left+16,top+11,36,36,18,'#fffefa');x.fillStyle='#617455';x.font='bold 22px sans-serif';x.fillText(String(n+1).padStart(2,'0'),left+20,top+37);
  x.font='22px sans-serif';x.fillText(n===0?'想象的起点':n===1?'故事开始啦':n===2?'接着发生了…':'暖暖的结尾',left+66,top+37);
  // A quiet brand watermark lives in each card's margin, never over the art.
  x.save();x.globalAlpha=.48;x.textAlign='right';x.font='20px sans-serif';x.fillText('画活了 ✧',left+w-22,top+36);x.restore();
  const imageX=left+18,imageY=top+70,imageW=w-36,imageH=419;
  rounded(imageX,imageY,imageW,imageH,15,'#f7f5ec');
  const scale=Math.min(imageW/im.width,imageH/im.height),iw=im.width*scale,ih=im.height*scale;
  const variant=snapshot.story.variants?.[n];x.save();x.beginPath();x.roundRect(imageX,imageY,imageW,imageH,15);x.clip();x.filter=variant==='warm'?'sepia(.28) saturate(1.15)':variant==='soft'?'saturate(.65) brightness(1.04)':'none';x.drawImage(im,imageX+(imageW-iw)/2,imageY+(imageH-ih)/2,iw,ih);x.restore();
  const caption=n===0?'故事，从这幅小小的画开始。':pageCaption(snapshot,n);
  let font=27,lines,lineHeight;do{x.font=`${font}px sans-serif`;lines=wrap(caption,w-56);lineHeight=Math.ceil(font*1.45);if(lines.length*lineHeight<=132||font<=12)break;font--;}while(true);
  x.fillStyle='#505c47';lines.forEach((line,k)=>x.fillText(line,left+28,top+523+k*lineHeight));
 });
 star(61,1524,15,'#dcb86f');x.fillStyle='#8c927d';x.font='20px sans-serif';x.fillText(snapshot.story.real?'第 1 页为原画 · 第 2–4 页为 AI 生成 · 请家长先阅':'预设故事示例',87,1532);
 x.fillStyle='#9b8c79';x.font='22px sans-serif';x.textAlign='center';x.fillText('画活了  ·  珍藏每一份小小想象',800,1578);x.textAlign='left';
 const output=c.toDataURL('image/png');if(current()?.id!==snapshot.id)return;
 modalMode='share';openModal('分享完整的四页故事',`<p class="muted">原画与三页续画组成四宫格，按左上、右上、左下、右下阅读。包含三页故事旁白，不附孩子原话、昵称或原声。请确认预览后保存。</p><img src="${output}" alt="四页故事四宫格分享预览" style="display:block;width:100%;max-width:560px;margin:20px auto;border-radius:6px"><p class="muted">接收者保存的图片无法撤回。不会生成公开阅读链接。</p><div class="actions"><button class="secondary" data-action="read">返回故事</button><button class="primary" id="download-share">保存四宫格图片</button></div>`);
 $('#download-share').onclick=()=>download(output,'画活了_四页故事.png');
}

function deletePrompt(){const i=current();modalMode='delete';openModal('确定告别这幅画吗？',`<p class="muted">将从当前浏览器删除「${esc(i.title)}」的原图、处理图、文字${i.audio?'、原声':''}、关联故事与调整记录${i.job?'，并取消进行中的演示':''}。已下载的副本不受影响。</p><div class="notice">删除后无法在此恢复。需要的话，请先返回导出。</div><div class="actions"><button class="secondary" data-action="detail" data-id="${i.id}">留着这份想象</button><button class="primary" style="background:#a57765" data-action="confirm-delete">确认删除</button></div>`)}
function privacy(){modalMode='privacy';openModal('让记录，安心留在这里',`<p class="muted">本地 demo 使用浏览器 IndexedDB 保存原图、处理图、文字及可选录音。原始记录默认仅存浏览器。选择真实 AI 测试并授权后，处理图、孩子的话、家长补充和设定会发送到本机服务端及 Poixe 模型服务；原声不发送。生成任务和结果保存到本机服务端 .local-data 中，不是云端备份。</p><div class="notice">这不是正式家庭试用服务；尚无独立家长账号或正式内容审核，现有访问控制仅绑定当前浏览器。请使用演示素材验证流程。</div><p class="muted">可以在作品详情下载原图和文字，也可在“我的”导出完整 JSON 备份。删除会移除本浏览器中的记录。清除网站数据、更换浏览器或设备后，记录可能不再可用。</p><div class="actions"><button class="primary" data-action="close">知道了</button></div>`)}
async function action(a,el){switch(a){case'nav':tab=el.dataset.value;render();break;case'backAlbum':tab='album';render();break;case'filter':filter=el.dataset.value;render();break;case'new':edit();break;case'close':if(modalMode==='edit'&&(draft?.original||[...($('#art-form')?.querySelectorAll('input[type=text],textarea')||[])].some(e=>e.value.trim()))){if(!confirm('这幅画还没有保存，确定离开吗？'))return}closeModal();break;case'detail':activeId=el.dataset.id||activeId;detail();break;case'sample':{let sample=items.find(i=>i.id==='sample-dog');if(!sample){sample=seed()[0];items.push(sample);await save();render()}activeId=sample.id;page=0;reader();break}case'rotate':case'crop':case'restore':await transformImage(a);break;case'record':await record();break;case'setup':setup();break;case'generate':await generate();break;case'real-generate':await realGenerate(el);break;case'real-recover':await realRecover();break;case'real-dismiss':delete current().job;await save();detail();break;case'status':status();break;case'cancel-job':if(current().job?.real){await cancelReal(current());break;}delete current().job;await save();render();detail();toast('故事演示已取消，原画仍然保留');break;case'read':page=current().story?.position||0;reader();break;case'prev':page--;reader();break;case'next':page++;reader();break;case'page':page=Number(el.dataset.value);reader();break;case'adjust':pendingTone='warm';adjust();break;case'tone':pendingTone=el.dataset.value;document.querySelectorAll('.adjust-options button').forEach(b=>b.classList.toggle('selected',b===el));break;case'preview-adjust':await previewAdjust();break;case'adopt':current().story.previous[page]=current().story.variants[page]||null;current().story.variants[page]=pendingTone;await save();reader();toast('已采用新图，可以撤销最近一次调整');break;case'undo':{const s=current().story;s.variants[page]=s.previous[page];delete s.previous[page];await save();reader();toast('已恢复上一版本，已使用次数不变');break}case'original':{const i=current();download(i.original,i.fileName||i.title+'.svg');break}case'export-text':{const i=current();downloadJSON({title:i.title,date:i.date,childWords:i.words,parentNotes:i.parent||'',source:i.sample?'预设示例':'家长记录大意'},i.title+'_原始文字.json');break}case'backup':downloadJSON({schema:'huahuole-local-demo-v1',exportedAt:new Date().toISOString(),artworks:items},'画活了_本地画册备份.json');break;case'print':printStory();break;case'share':await share();break;case'delete':deletePrompt();break;case'confirm-delete':{const target=current();const remoteId=target.job?.real?target.job.id:target.story?.real?target.story.jobId:null;if(remoteId){try{await api('/api/jobs/'+remoteId,{method:'DELETE'})}catch(e){if(e.status!==404)throw e;}}const before=items;items=items.filter(i=>i.id!==activeId);try{await save()}catch(e){items=before;throw e}closeModal();render();toast('这幅作品及其关联记录已从本机删除');break}case'privacy':privacy();break;}}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el&&!el.disabled)action(el.dataset.action,el).catch(err=>{console.error(err);toast('操作未完成，请重试。若存储空间不足，请先导出并清理记录。')})});
document.addEventListener('change',e=>{if(e.target.id==='image-file')selectImage(e.target.files[0]).catch(()=>{e.target.value='';toast('图片无法解码，请换一张图片。')});if(e.target.classList.contains('sort')){sort=e.target.value;render()}});
document.addEventListener('submit',e=>{if(e.target.id==='art-form'){e.preventDefault();saveArtwork(e.target,e.submitter?.value||'generate').catch(()=>toast('保存失败，当前填写内容已保留，请重试。'))}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modalMode)action('close',{});if(modalMode==='reader'&&!['INPUT','TEXTAREA'].includes(e.target.tagName)){if(e.key==='ArrowRight'&&page<3){page++;reader()}if(e.key==='ArrowLeft'&&page>0){page--;reader()}}if(e.key==='Tab'&&modalMode){const list=[...document.querySelectorAll('.modal button:not(:disabled),.modal input,.modal textarea,.modal select,.modal audio')];const first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}});
window.addEventListener('beforeunload',e=>{if(modalMode==='edit'&&draft?.original){e.preventDefault();e.returnValue=''}});
async function init(){db=await new Promise((resolve,reject)=>{const r=indexedDB.open('huahuole-demo',1);r.onupgradeneeded=()=>r.result.createObjectStore('data');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});const existing=await transaction('readonly',s=>s.get('artworks'));items=existing??seed();if(!existing)await save();render();await initAI();await tick();setInterval(()=>tick().catch(()=>toast('演示状态保存失败，请重试')),1500)}
init().catch(()=>{$('#app').innerHTML='<div class="empty"><h2>当前浏览器无法使用本地存储</h2><p>请退出无痕模式或允许网站存储，然后刷新重试。</p></div>'});

let clientToken='',aiConfig={configured:false},pollBusy=false;
async function initAI(){clientToken=await transaction('readonly',s=>s.get('client-token'));if(!clientToken){clientToken=Array.from(crypto.getRandomValues(new Uint8Array(32)),v=>v.toString(16).padStart(2,'0')).join('');await transaction('readwrite',s=>s.put(clientToken,'client-token'));}try{aiConfig=await api('/api/config')}catch{}}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json','X-Client-Token':clientToken,...options.headers},signal:AbortSignal.timeout(20000)});let data;try{data=await response.json()}catch{throw new Error('服务未更新或未启动，请重启本机服务。')}if(!response.ok)throw Object.assign(new Error(data.error||'请求失败'),{status:response.status});return data;}
async function realSetup(){const i=current();modalMode='real-setup';try{aiConfig=await api('/api/config')}catch(e){aiConfig={configured:false,error:e.message}}openModal('让这幅画，真的讲个故事',`<p class="muted">原画已独立保存。第 1 页使用原画，第 2–4 页由 AI 参考这幅画续绘，适度整理角色的线条、比例和神态，保留主色、独特特征与童趣。图文分开排版。</p><div class="story-premise"><span class="source">${i.parent||i.words?'沿用刚才的描述':'没有填写也没关系'}</span><p>${esc(i.parent||i.words||'围绕画里的主体，发生一件温和的小事。')}</p></div><details class="more-records"><summary>想换个故事方向？ <span>可选</span></summary><label class="field">故事方向<textarea id="real-setting" maxlength="150">${esc((i.parent||i.words||'围绕原画中的主体，发生一件温和的小事。').slice(0,150))}</textarea></label></details>${aiNotice()}${!aiConfig.configured?`<div class="notice">${esc('生成暂不可用，请联系体验负责人；原画仍可保存。')}</div>`:''}<label class="check"><input id="real-consent" type="checkbox">同意将处理图和文字发送给 Poixe 及其上游 AI 生成故事，已阅读数据使用与费用说明。</label><div class="actions"><button class="secondary" data-action="detail" data-id="${i.id}">先只保存原画</button><button class="primary" data-action="real-generate" ${!aiConfig.configured?'disabled':''}>生成故事</button></div>`);}
async function processingImage(src){const im=await loadImage(src),scale=Math.min(1,1024/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.drawImage(im,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.9);}
async function realGenerate(button,prepared=null){if(!(prepared?.consent||$('#real-consent')?.checked))return toast('请先确认 AI 数据使用说明');const setting=(prepared?.setting??$('#real-setting')?.value??'').trim();if(!setting)return toast('请填写一句话设定');const i=current();button.disabled=true;try{const image=await processingImage(i.image);const id=crypto.randomUUID();i.job={id,real:true,started:Date.now(),state:'SUBMITTING',stage:'正在提交',request:{id,image,setting,words:i.words||'',parent:i.parent||'',consent:true}};await save();realStatus();try{const result=await api('/api/jobs',{method:'POST',body:JSON.stringify(i.job.request)});Object.assign(i.job,result);delete i.job.request;}catch(e){i.job.error=e.message;i.job.state='SUBMITTING';i.job.stage='提交结果待确认';}await save();render();realStatus();}catch(e){toast(e.message);button.disabled=false;}}
function realStatus(){const i=current(),j=i?.job;if(!j?.real)return;modalMode='real-status';openModal('故事正在准备',`<div class="wait-graphic">${['FAILED','CANCELLED','SUBMITTING'].includes(j.state)?'!':'✧'}</div><h3 class="wait-title">${esc(j.stage||'等待处理')}</h3><p class="muted" style="text-align:center">原画已保存。可以离开页面，稍后从这幅画找回。<br>四页完成后一起阅读，请家长先看一遍。</p>${j.error?`<div class="notice">${esc(j.error)}</div>`:''}<details class="ai-disclosure"><summary>查看任务信息</summary><p class="source">模型：${esc(j.model||'gemini-2.5-flash-image')}<br>任务：${j.id}<br>30 分钟未完成则停止，原画不受影响。</p></details><div class="actions">${['WAITING_RECOVERY','SUBMITTING'].includes(j.state)?'<button class="primary" data-action="real-recover">'+(j.state==='SUBMITTING'?'确认提交状态':'找回已有结果')+'</button>':''}${['FAILED','CANCELLED'].includes(j.state)?'<button class="secondary" data-action="real-dismiss">返回原画</button>':'<button class="secondary" data-action="cancel-job">取消任务</button>'}<button class="secondary" data-action="close">返回画册</button></div>`);}
async function realRecover(){const i=current(),j=i.job;try{let result;if(j.state==='SUBMITTING'){result=await api('/api/jobs',{method:'POST',body:JSON.stringify(j.request)});}else result=await api('/api/jobs/'+j.id+'/recover',{method:'POST',body:'{}'});Object.assign(j,result);delete j.request;await save();realStatus();}catch(e){toast(e.message)}}
async function cancelReal(i){try{try{await api('/api/jobs/'+i.job.id+'/cancel',{method:'POST',body:'{}'})}catch(e){if(e.status!==404)throw e;}delete i.job;await save();render();detail();toast('已取消，运行中的上游调用可能仍计费，返回结果不会交付。')}catch(e){toast(e.message)}}
async function pollRealJobs(){if(pollBusy||!clientToken)return;pollBusy=true;try{for(const i of items){const j=i.job;if(!j?.real||j.state==='SUBMITTING')continue;let result;try{result=await api('/api/jobs/'+j.id)}catch{continue}if(!items.includes(i)||i.job?.id!==j.id)continue;if(result.state==='READY'){for(const p of result.pages)await loadImage(p.image);i.story={real:true,ready:true,jobId:j.id,pages:result.pages,sourceImage:result.sourceImage,words:result.words,setting:result.setting,delivered:Date.now(),position:0,variants:{},previous:{},adjustments:0};delete i.job;await save();render();if(activeId===i.id&&['real-status','status'].includes(modalMode)){page=0;reader();}toast('故事准备好了，先看看，再一起读。');}else if(j.state!==result.state||j.stage!==result.stage||j.error!==result.error){Object.assign(j,result);await save();if(activeId===i.id&&modalMode==='real-status')realStatus();}}}finally{pollBusy=false;}}

function aiNotice(){return `<p class="muted" style="margin-top:18px">一幅原画，三页 AI 续画，做成一本静态图文故事。</p><details class="ai-disclosure"><summary>数据使用与费用说明</summary><p class="muted">处理图、描述及可选的孩子原话会发送至 Poixe 及上游模型，可能涉及境外处理；原声不发送。生成任务与结果还会保存到提供服务的本机。中断请求据服务方文档暂存 3 天，完整留存与训练政策仍待核验，请仅使用已获授权的素材。生成会使用服务端账号余额，费用以服务方账单为准；当前没有向家长收款的入口。结果尚未经过正式内容审核，请家长先查看。</p></details>`;}
