import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {mkdtemp,writeFile,rm,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import assert from 'node:assert/strict';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_PATH||'playwright');
const dir=await mkdtemp(join(tmpdir(),'huahuole-ui-'));const mock=join(dir,'mock.mjs');
const png=(await readFile('test-results/upload.png')).toString('base64');
await writeFile(mock,`globalThis.fetch=async(url,options)=>{if(!url.startsWith('https://api-eu-central-1-dc8.poixe.com/'))throw new Error('Unexpected host');const plan={characters:'蓝色小狗',pages:[1,2,3].map(n=>({text:'小狗来到池塘边，和月亮一起看夜空。',prompt:'Blue dog '+n}))};return Response.json(url.includes('/chat/')?{choices:[{message:{content:JSON.stringify(JSON.parse(options.body).messages[0].content.includes("检查员")?{passed:true,issues:[]}:plan)}}]}:{candidates:[{content:{parts:[{inlineData:{mimeType:'image/png',data:'${png}'}}]}}]})};`);
const server=spawn(process.execPath,['--import',mock,'server.mjs'],{env:{...process.env,PORT:'5184',STORY_DATA_DIR:join(dir,'data'),POIXE_API_KEY:'fixture-only'},stdio:['ignore','pipe','pipe']});
let browser;
try{await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('exit',c=>reject(new Error('Server exit '+c)))});
 browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:5184');await page.getByRole('button',{name:'留下一幅画',exact:true}).click();await page.getByLabel('选择画作').setInputFiles('test-results/upload.png');await page.getByAltText('处理图预览').waitFor();assert.equal(await page.locator('input[name=title]').isVisible(),false);assert.equal(await page.locator('textarea[name=words]').isVisible(),false);await page.locator('textarea[name=parent]').fill('真实接口流程测试');await page.locator('input[type=checkbox][required]').check();let submissions=0;page.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith('/api/jobs'))submissions++});await page.getByRole('button',{name:'生成故事',exact:true}).click();await page.getByText('请先确认 AI 使用说明；也可以选择只保存原画。',{exact:true}).waitFor();assert.equal(submissions,0);await page.locator('#ai-upload-consent').check();await page.getByRole('button',{name:'生成故事',exact:true}).click();await page.getByRole('button',{name:'下一页 →'}).waitFor({timeout:15000});await page.getByRole('button',{name:'下一页 →'}).click();await page.getByText('AI 生成 · 请家长先阅 · 2 / 4',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'调整这一页'}).count(),0);await page.screenshot({path:'test-results/ai-reader.png',fullPage:true});await page.reload();await page.getByRole('button').filter({has:page.getByRole('heading',{name:'真实接口流程测试',exact:true})}).click();await page.getByRole('button',{name:'一起读这个故事'}).click();await page.getByText('AI 生成 · 请家长先阅 · 2 / 4',{exact:true}).waitFor();
 for(const path of ['/.env','/.local-data/jobs/test.json','/backend/jobs.mjs','/scripts/poixe-smoke.mjs'])assert.equal((await page.request.get('http://localhost:5184'+path)).status(),404);
 await page.getByRole('button',{name:'分享图片',exact:true}).click();await page.getByAltText('四页故事四宫格分享预览').waitFor();const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'保存四宫格图片'}).click();await (await downloadPromise).saveAs('test-results/share-grid.png');const grid=await readFile('test-results/share-grid.png');assert.equal(grid.readUInt32BE(16),1600);assert.equal(grid.readUInt32BE(20),1600);assert.equal(submissions,1);assert.deepEqual(errors,[]);console.log('PASS: upload → consent → server job → 4-page reader → reload, source labels, no fake AI adjustments, private static paths blocked. Mock provider only.');
}finally{if(browser)await browser.close();server.kill('SIGTERM');await new Promise(r=>server.exitCode!==null?r():server.once('exit',r));await rm(dir,{recursive:true,force:true})}
