import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const context=await browser.newContext({viewport:{width:1440,height:1080},acceptDownloads:true});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await mkdir('test-results',{recursive:true});
try{
 await page.goto('http://localhost:5173');await page.getByRole('heading',{name:'小小画册，大大世界'}).waitFor();
 await page.screenshot({path:'test-results/desktop.png',fullPage:true});
 await page.locator('.card').first().locator('img').screenshot({path:'test-results/upload.png'});
 await page.getByRole('button',{name:'翻开四页示例'}).click();
 await page.getByRole('button',{name:'下一页 →'}).click();
 await page.getByRole('button',{name:'调整这一页'}).click();
 await page.getByRole('button',{name:'生成演示预览'}).click();
 await page.getByRole('button',{name:'采用这张'}).click();
 assert.match(await page.locator('.reader-image').getAttribute('style'),/sepia/);
 await page.getByRole('button',{name:'调整这一页'}).click();
 await page.getByRole('button',{name:'撤销最近采用的调整'}).click();
 assert.equal(await page.locator('.reader-image').getAttribute('style'),'');
 await page.getByRole('button',{name:'分享图片',exact:true}).click();
 const sharePromise=page.waitForEvent('download');await page.getByRole('button',{name:'保存四宫格图片'}).click();await (await sharePromise).saveAs('test-results/share.png');
 await page.getByRole('button',{name:'关闭',exact:true}).click();
 await page.getByRole('button',{name:'留下一幅画',exact:true}).click();
 await page.getByLabel('选择画作').setInputFiles('test-results/upload.png');
 await page.getByAltText('处理图预览').waitFor();
 await page.locator('.more-records summary').click();
 await page.locator('input[name=title]').fill('自动验证的画');
 await page.locator('textarea[name=words]').fill('小狗今天想去看星星。');
 await page.getByRole('button',{name:'旋转 90°'}).click();
 await page.locator('input[type=checkbox][required]').check();
 await page.getByRole('button',{name:'只保存原画'}).click();await page.getByRole('button').filter({has:page.getByRole('heading',{name:'自动验证的画',exact:true})}).click();
 await page.getByRole('heading',{name:'这一幅，值得记住'}).waitFor();
 const origPromise=page.waitForEvent('download');await page.getByRole('button',{name:'下载原图'}).click();await (await origPromise).saveAs('test-results/original.png');
 const {readFile}=await import('node:fs/promises');assert.deepEqual(await readFile('test-results/upload.png'),await readFile('test-results/original.png'));
 await page.getByRole('button',{name:'一起做个故事'}).click();await page.getByRole('heading',{name:'让这幅画，真的讲个故事'}).waitFor();assert.equal(await page.getByRole('button',{name:'生成故事',exact:true}).isDisabled(),true);
 await page.reload();await page.getByRole('heading',{name:'自动验证的画',exact:true}).waitFor();
 await page.getByRole('button').filter({has:page.getByRole('heading',{name:'会唱歌的花园',exact:true})}).click();
 await page.getByRole('button',{name:'一起做个故事'}).click();await page.locator('#demo-consent').check();await page.getByRole('button',{name:'开始免费演示'}).click();
 await page.getByRole('button',{name:'取消本次演示'}).click();await page.getByRole('button',{name:'一起做个故事'}).click();await page.locator('#demo-consent').check();await page.getByRole('button',{name:'开始免费演示'}).click();
 await page.getByRole('heading',{name:'小小故事，正在准备'}).waitFor();await page.reload();await page.getByRole('button').filter({has:page.getByRole('heading',{name:'会唱歌的花园',exact:true})}).click();
 await page.getByRole('button',{name:'查看演示进度'}).click();await page.getByRole('button',{name:'下一页 →'}).waitFor({timeout:15000});
 await page.getByRole('button',{name:'关闭',exact:true}).click();
 await page.getByRole('button').filter({has:page.getByRole('heading',{name:'自动验证的画',exact:true})}).click();await page.getByRole('button',{name:'删除这幅作品'}).click();await page.getByRole('button',{name:'确认删除',exact:true}).click();await page.getByRole('heading',{name:'自动验证的画',exact:true}).waitFor({state:'hidden'});
 await page.reload();await page.getByRole('heading',{name:'小小画册，大大世界'}).waitFor();assert.equal(await page.getByRole('heading',{name:'自动验证的画',exact:true}).count(),0);
 for(const width of [360,390,430]){await page.setViewportSize({width,height:844});await page.screenshot({path:`test-results/mobile-${width}.png`,fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);}
 await page.getByRole('button',{name:'翻开四页示例'}).click();await page.screenshot({path:'test-results/mobile-reader.png',fullPage:true});
 assert.deepEqual(errors,[]);console.log('PASS: reader, adjustment + undo, share export, upload + rotate, original byte preservation, reload persistence, AI boundary, cancellation, job recovery, deletion, 360/390/430 layouts; no page errors.');
}catch(error){await page.screenshot({path:'test-results/failure.png',fullPage:true});console.log(await page.locator('body').innerText());throw error}finally{await browser.close()}
